### ISSUE TITLE
under gjrand

### ISSUE THREAD

**Issue by tankf33der** [espadrine/shishua#4]
[gjrand](http://gjrand.sourceforge.net/) is so cool toolset it used for stars qualifications for PRGs in [PracRand](http://pracrand.sourceforge.net/RNG_engines.txt) (chapter 3).

there is summary run for shishua, easy to check and repeat:
```
o) mcp --tiny
completed 13 tests
9 out of 13 tests ok.
4 grade 1 failures (probably ok).
o) mcp --small
completed 13 tests
13 out of 13 tests ok.
o) mcp --standard
completed 13 tests
13 out of 13 tests ok.
o) mcp --big
completed 13 tests
10 out of 13 tests ok.
3 grade 1 failures (probably ok).
```

**Comment by tankf33der** [comment]
and i see different summary if run shishua with "--seed", small and standard tests are not "13 out of 13 tests ok" anymore.

**Comment by espadrine** [comment]
I love gjrand! I tested SHISHUA with --huge also, which passed.

The nature of p-value testing, which I talk about [here](https://espadrine.github.io/blog/posts/a-primer-on-randomness.html), causes a requirement for random generators (even TRNGs) to fail some tests sometimes, but the failures should appear as the extrema of a uniform distribution over the range of possible p-values.

So, across the huge space of all seeds, there must exist one where SHISHUA does not pass mcp --huge, but:

- that is true for all generators, including TRNGs, and therefore does not mean that the output was not random,
- it should be unlikely.

Thus the only way to have a marginal level of confidence that a generator is random, is to perform the test suite on all seeds, which is obviously impossible, and the test suite is not exhaustive anyway.
