### ISSUE TITLE
best seeds?

### ISSUE THREAD

**Issue by ghost** [espadrine/shishua#8]
Hi,
Are there seeds you suggest to be used for a better distribution ? Or is it not important ?
I have to generate 16MB of random data.

Thanks

**Comment by TheIronBorn** [comment]
Per the announcement blogpost:
> The counter is not necessary to beat PractRand. Its only purpose is to set a lower bound of 269 bytes = 512 EiB to the period of the PRNG: we only start repeating the cycle after one millenia at 10 GiB/s, which is unlikely to ever be too low for practical applications in the coming centuries. Thanks to this, ***there are no bad seeds.***

**Comment by ghost** [comment]
Nice, thanks
